/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader */

#ifndef _Included_xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader
#define _Included_xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader
 * Method:    hook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader_hook
  (JNIEnv *, jclass);

/*
 * Class:     xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader
 * Method:    unhook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_tbvns_ghostTrainer_Inputs_NativeMouseReader_unhook
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
